### ISSUE TITLE
An error happened while checking commit

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/gerrit-eca-plugin#26] opened 2020-11-30 18:52 UTC
```
| 13:43 <git:(cguindon/7.x-4.x/empty-ob)> % git push origin HEAD:refs/for/7.x-4.x
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 463 bytes | 154.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3)
remote: Processing changes: refs: 1, done    
remote: commit bae087b: warning: too many message lines longer than 72 characters; manually wrap lines
To ssh://.../drupal/custom/common/site_login
 ! [remote rejected] HEAD -> refs/for/7.x-4.x (commit bae087b: An error happened while checking commit)
error: failed to push some refs to 'ssh://cguindon@foundation.eclipse.org:29418/drupal/custom/common/site_login'
```

**Comment by autumnfound** [comment] 2020-11-30 19:11
So ways I attempted to reproduce, I checked out upstream/master:
```  
❯ git status
HEAD detached at upstream/master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/main/resources/application.properties
no changes added to commit (use "git add" and/or "git commit -a")
❯ git fetch upstream
Enter passphrase for key '/home/martin/.ssh/id_rsa': 
```  
The changed file is me tweaking the port locally to test since I use the port it usually runs on.
Using the same data (included below the HTTP responses I've included), I attempt to hit api.eclipse.org and then my localhost version of the server.

API.eclipse.org:  
``` 
> POST /git/eca HTTP/1.1
> Host: api.eclipse.org
> User-Agent: insomnia/2020.3.3
> Cookie: ECLIPSESESSION=15f9242228eb9e783f08b8ac15e180f5
> Content-Type: application/json
> Accept: */*
> Content-Length: 617
| {
|    "repoUrl":"http://git.git/gitroot/e4/eclipse.platform.runtime.e4.git",
|    "commits":[
|       {
|          "hash":"b0e9ff84a121fb3e468c56fda8d1fe44ed1c2864",
|          "subject":"Test",
|          "body":"Test Change-Id: Ice1eb2f662dc9f83cba25ef23a4d600a903b969f",
|          "parents":[
|             ""
|          ],
|          "author":{
|             "name":"Martin Lowe",
|             "mail":"martin.lowe@eclipse-foundation.org"
|          },
|          "committer":{
|             "name":"Martin Lowe",
|             "mail":"martin.lowe@eclipse-foundation.org"
|          },
|          "head":true
|       }
|    ],
|    "provider":"gerrit"
| }
* upload completely sent off: 617 out of 617 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Mon, 30 Nov 2020 19:03:39 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://api.eclipse.org/git/eca
* Ignoring the response-body
* Received 162 B chunk
* Connection #6 to host api.eclipse.org left intact
* Issue another request to this URL: 'https://api.eclipse.org/git/eca'
* Switch from POST to GET
* Found bundle for host api.eclipse.org: 0x317fccfcce70 [can multiplex]
* Re-using existing connection! (#4) with host api.eclipse.org
* Connected to api.eclipse.org (198.41.30.211) port 443 (#4)
* Using Stream ID: 5 (easy handle 0x317fd0ceb000)
> GET /git/eca HTTP/2
> Host: api.eclipse.org
> user-agent: insomnia/2020.3.3
> cookie: dc1b1b4357beb4af1a14875bec958b0a=cf405092d3ace5a9583488c97fd0e08a; ECLIPSESESSION=15f9242228eb9e783f08b8ac15e180f5
> content-type: application/json
> accept: */*
< HTTP/2 500 
< server: nginx
< date: Mon, 30 Nov 2020 19:03:39 GMT
< content-length: 0
```  

localhost:  
```  
> POST /git/eca HTTP/1.1
> Host: localhost:8090
> User-Agent: insomnia/2020.3.3
> Cookie: JSESSIONID=A1jaYoB8fx50phJczvCfPUW3yOLVoHxBuOF2HBvl
> Content-Type: application/json
> Accept: */*
> Content-Length: 617
| {
|    "repoUrl":"http://git.git/gitroot/e4/eclipse.platform.runtime.e4.git",
|    "commits":[
|       {
|          "hash":"b0e9ff84a121fb3e468c56fda8d1fe44ed1c2864",
|          "subject":"Test",
|          "body":"Test Change-Id: Ice1eb2f662dc9f83cba25ef23a4d600a903b969f",
|          "parents":[
|             ""
|          ],
|          "author":{
|             "name":"Martin Lowe",
|             "mail":"martin.lowe@eclipse-foundation.org"
|          },
|          "committer":{
|             "name":"Martin Lowe",
|             "mail":"martin.lowe@eclipse-foundation.org"
|          },
|          "head":true
|       }
|    ],
|    "provider":"gerrit"
| }
* upload completely sent off: 617 out of 617 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Content-Length: 567
< Content-Type: application/json
```  
JSON Data:  
```  
{
   "repoUrl":"/gitroot/e4/eclipse.platform.runtime.e4.git",
   "commits":[
      {
         "hash":"b0e9ff84a121fb3e468c56fda8d1fe44ed1c2864",
         "subject":"Test",
         "body":"Test Change-Id: Ice1eb2f662dc9f83cba25ef23a4d600a903b969f",
         "parents":[
            ""
         ],
         "author":{
            "name":"Martin Lowe",
            "mail":"martin.lowe@eclipse-foundation.org"
         },
         "committer":{
            "name":"Martin Lowe",
            "mail":"martin.lowe@eclipse-foundation.org"
         },
         "head":true
      }
   ],
   "provider":"gerrit"
}
```

**Comment by autumnfound** [comment] 2020-11-30 19:12
This looks to be an issue with the API that is bubbling up to gerrit. I'm investigating that now

**Comment by autumnfound** [comment] 2020-11-30 19:31
I've added a more useful message for this case over the current message.

Old message:
`An error happened while checking commit`

New message:
`An error happened while retrieving validation response, please contact the administrator if this error persists`

**Comment by autumnfound** [comment] 2020-11-30 21:07
Closing this issue as it was solved with a rebuild, added additional logging in case this happens again

**Closed by autumnfound** 2020-11-30 21:07 UTC
